### ISSUE TITLE
Bitcode enabled

### ISSUE THREAD

**Issue by Flash3001** [kikettas/xamapod#1]
Hey @kikettas. 

This project is great! I didn't have time to test it yet, but I will definitely be using it. Just wanted to check one thing. 

https://github.com/kikettas/Xamapod/blob/master/build#L87

Is doing **ENABLE_BITCODE=YES** but it should say **NO**. If one library is using bitcode all the other ones and the main project should as well. Xamarin for WatchOS supports BITCODE as it is mandatory, but not for iOS. I might be wrong though, checked it last time more than 2 years ago.

**Comment by kikettas** [comment]
True, probably I missed that while testing the `otool -l yourlib.a | grep __LLVM` command to see if it was working. Good catch 👍
